In [3]:
import numpy as np
import pandas as pd
df=pd.read_csv('Countries.csv')
df.head(3)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President

In [7]:
#which country has highest population
df[df['population']==df['population'].max()][['country','population']]

   country  population
75   India  1417173173

In [ ]:
#capital of country with highest population
df[df['population']==df['population'].max()]['capital_city']

75    New Delhi
Name: capital_city, dtype: object

In [9]:
#give top5 countries with highest democratic score
df.nlargest(5,'democracy_score')['country']

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

In [11]:
df.sort_values(by='democracy_score',ascending=False,inplace=True)
df['country'].head(2)

127     Norway
74     Iceland
Name: country, dtype: object

In [13]:
#how many total regions are there
df['region'].value_counts().count()

np.int64(22)

In [14]:
#how many countries lie in eastern europe region
df[df['region']=='Eastern Europe']['country']

43      Czech Republic
151    Slovak Republic
24            Bulgaria
136             Poland
73             Hungary
139            Romania
111            Moldova
181            Ukraine
14             Belarus
140             Russia
Name: country, dtype: object

In [18]:
#who is political leader of 2nd highest populated country
df[df['population']==df['population'].nlargest(2).iloc[1]]['political_leader']

34    Xi Jinping
Name: political_leader, dtype: object

In [19]:
#how many countries whose political leaders are unknown
df[df['political_leader'].isna()]['country'].count()

np.int64(7)

In [21]:
#how many country have republic in their full name
count=0
def counting(txt):
    global count
    if 'republic' in txt.lower():
        count+=1
    return txt
df['country_long']=df['country_long'].apply(counting)
print(count)

125

In [22]:
#which country in african region has highest population
african_df=df[df['continent']=='Africa']
african_df[african_df['population']==african_df['population'].max()]['country']

125    Nigeria
Name: country, dtype: object